config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get '/' => 'home#index'
  get '/job' => 'job#index'
  get '/profile' => 'profile#index'
  get '/project' => 'project_entry#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/projectEntry.rb
class ProjectEntry < ApplicationRecord
  include ActiveModel::API
  attribute :title, :string
  attribute :content, :string


  def new(title, content)
    p = ProjectEntry.new
    p.title = title
    p.content = content
    p.save
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render :'home/index'
  end
end

app/controllers/job_controller.rb
class JobController < ApplicationController
  def index
    render :template => 'job/index'
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
    render :'profile/index'
  end
end

app/controllers/project_entry_controller.rb
class ProjectEntryController < ApplicationController
  def index
    render :template => 'project_entry/index'
  end

  def list
    @projectEntries = ProjectEntry.all
  end
  def create
    @projectEntries.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/job_helper.rb
module JobHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/project_entry_helper.rb
module ProjectEntryHelper
end

app/views/home/index.html.erb
<div class="home-title inside-title">
  <h2>Shiou-ping Chu, 3734303</h2>
</div>
<div class="inside-body">
  <div class="home-container">
    <div class="inside-content">
      <h3>Origin: Taiwan</h3>
      <h3>s3734303@student.rmit.edu.au</h3>
      <h3>Language: Chinese/English</h3>
      <h3>Hobby: Video game, music, computer hardware, internet bloodsports</h3>
      <div>
        <h3>Lore:</h3>
        <p style="width: 700px">
          Originally enrolled to software engineering, but unable to find an internship and failed on AI and computing theory, so I was cast down to Information technology.
        </p>
      </div>
      <div>
        <h3>Education</h3>
        <p>Information Technology (2022)</p>
        <p>Software Engineering (2019-2021)</p>
        <p>[REDACTED] (-2018)</p>

      </div>
    </div>
  </div>
  <div class="my-photo">
    <img class="profile" src="https://melmagazine.com/wp-content/uploads/2021/01/66f-1.jpg" width="400" alt="me fr">
  </div>
</div>

<div class="home-container">
  <div class="inside-content home-container">
    <div>
      <h2>Interest in IT</h2>
      <div>
        <h3>What is your interest in IT? When did your interest in IT start?</h3>
        <p>Mostly started from video game, then building computer, eventually start trying to write code to see if I can do it myself and to peek what it looks like behind the scenes. </p>
      </div>
      <div>
        <h3>Why did you choose to come to RMIT?</h3>
        <p>After some massive academic failure back in home country I decided to make a last-ditch effort to turn my life around, picked RMIT because name sounds dope and it's in city, so I don't have to worry about transport.</p>
      </div>
      <div>
        <h3>What do you expect to learn during your studies?</h3>
        <p>I probably learned most thing I need to learn already this semester is mostly an overtime due to all the unfortunate circumstances.</p>
      </div>
    </div>
    </div>
  <div class="my-photo">
    <img src="https://w0.peakpx.com/wallpaper/233/587/HD-wallpaper-giga-chad-hair-memes.jpg" width="400" alt="me fr">
  </div>
</div>

app/views/job/index.html.erb
<h1 class="inside-title">Ideal Job</h1>
<div class="inside-content">
  <a href="https://archive.ph/vfP3P">Software Engineer (Sydney or Melbourne based) </a>
  <div>
    <h2>Description and Interest</h2>
    <p>
      A leading position in a sized Java-based software developing team which includes architect design and quality control. This role involved project managing and pipeline control, which are what I've learned for the past few years so naturally a job I'm interested, after all I don't want my works in RMIT go to waste.
    </p>
  </div>
  <div>
    <h2>Skill requirements</h2>
    <div>
      <p>
        •	Java along with framework system (Spring Soot) and dependency manager like Gradle and Maven (Yes)<br>•	Continuous Integration with CircleCI (I some what learned the concept form Software Engineering - Process & Tools but have little understanding, might need to revise on this subject)<br>
        •	Relational Database such as SQL (Yes)<br>
        •	Web API (I have certain degree of knowledge on API design)<br>
        •	AWS (I have knowledge and EC2, Beanstalk, DynamoDB)<br>
        •	Git and GitHub (Yes)<br>
        •	Docker (I have experiences in container deployment setup but never really build an image, the think I can try is build small applications in container as practice)<br>
        •	Data ETL (I have no idea what this so probably need to go on internet and learn it myself)<br>
        •	7+ years of work experience (self explanatory also a catch-22 problem)<br>
        •	Experience in finance and marketing industries (I have never touch such of things, maybe start from some entry position in financial institution)<br>
      </p>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<header>
  <div class="global-nav">
    <nav>
      <div id="global-nav-content">
        <ul>
          <li class="global-nav-item"><a><%= link_to 'Assignment 1', root_path %></a></li>
          <li class="global-nav-item"><a><%= link_to 'profile', profile_path%></a></li>
          <li class="global-nav-item"><a><%= link_to 'idea job', job_path%></a></li>
          <li class="global-nav-item"><a><%= link_to 'project', 'project'%></a></li>
        </ul>
      </div>
    </nav>
  </div>
  <a><br><br></a>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IntroA1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/project_entry/index.html.erb
<h1 class="inside-title">Project</h1>
<div class="inside-title">
  <h2>Web3 Shopping website application<br></h2>
  <div class="inside-content">
    <div>
      <h2>Overview</h2>
      <div>
        <p>An online shopping platform where we allow user to buy and sell items with each other. This website will be compatible with both desktop and mobile environment, as well as basic theme options like light and dark mode. Buyer can browse and search item through keyword and trending, after creating an account they can add these items to shopping cart and later check out. This platform will have a database system to keep everything in track. Unlike conventional online store front, we allow our buyer and seller accept the crypto of their choice, not just cryptocurrency but non fungible token if seller accept its perceived value, we also give buyer an additional option to mint their invoice into NFT as part of web3 integration.</p>
      </div>
    </div>
      <div>
        <h2>Motive</h2>
        <div>
          <p>
            Despite the booming of web3 and metaverse, most of the online shopping site still using traditional means for monetary transaction, as we see many examples of big tech & big finance censorship on individual with the "wrong think". One way they cut off these poor fellas is by denied payment though conventional services like VISA and Mastercard. My goal is to provide a platform to sell their product (like merchandises of certain kind of internet streamer /celebrities), free from the grasp big tech companies and their puppet master. On top of that web3 has promise us the idea of monetizing our online activity instead of let Facebook does it for us. We allow buyer to use their NFTs as a form of currency, even resell the receipt of purchase as commodity itself.
          </p>
        </div>
      </div>
      <div>
        <h2>Description</h2>
        <div>
          <p>
            The platform will mainly be accessed through web browser, a search bar that allows users entering keyword to search product and beneath that is the homepage that display trending item. Anyone can browse website but for any further will require user registration.  After created account user can now placing order as well as listing items. Before checking out user can add stuffs to shopping cart to check out later. Seller has the option of set whether it's a buy it now or auction item, and the currencies they will accept, buyer can also offer NFT as payment should the buyer accept. For account management user can change their display name, password.... thought a profile portal.
            Because this is a web3 platform we plan to integrate blockchain technology as part of our system. This will be our method to facilitate financial transaction, because blockchain is decentralized our service will be resilient to embargo from external financial services, although this mean any transaction with crypto will be on chain. After transaction complete, we also give user the option to mint their invoice as NFT.
            Beside traditional goods it is also a platform to trade, bid and sell NFTs as they're physical entities, because the future is web3 and metaverse want to see for NFTs with genuine utilities like tickets or a prove of ownership for something conceptual which cannot be enforce by traditional copyright or IP law.
          </p>
        </div>
      </div>
      <div>
      <div>
        <h2>Tools and technology</h2>
        <div>
          <p>
            This system will be built on ruby on rails.  Rails is a framework for rapid application development which cover both front and backend that use the model views controller paradigm, which simplify the process of website rendering and backend database handling.
            To keep track user and items we'll PostgreSQL or other similar relational database system, SQL is rigid compares to document-based database like MongoDB makes it suitable for our application as it involved financial transaction.
            Ethereum library is used to handle transaction of crypto and NFT.
            The application will be hosted on a cloud platform, so we don't have to pay for upfront equipment cost.<br>
            Our IDE choice will be IntelliJ IDEA.
          </p>
        </div>
      </div>
    <div>
      <h2>Skill requirement</h2>
      <div>
        <p>
          Because we're using ruby on rails the ability to code in Ruby is essential, ruby is a scripting language that in many ways similar to python, while there's a learning curve it shouldn't be a huge barrier, however, to ensure website function properly we also need to know how to use Rails API like session and cookies. To make website appealing, html, CSS, JavaScript skills are important, these are entry languages that should be readily for the most aspiring programmers.
          Knowledge of blockchain and its implementation would probably be the biggest hurdle, since I never have any experience in blockchain programming. But consider how many blockchain project and NFT rug pull out there it shouldn't be that hard to learn.
        </p>
      </div>
    </div>
        <div>
          <h2>Outcome</h2>
          <div>
            <p>
              Once complete, we should have a website with interface kin to mainstream shopping site, but more importantly, a step to make cryptocurrency a viable option for commerce and not just finance tool for speculation. While people buying real commodities online with bitcoin directly isn't a new idea, it was first adopted by illegal operations like drugs and document forgery, we want crypto being used in day-to-day purchase.
            </p>
          </div>
        </div>
      </div>
  </div>
</div>